services:
  - type: web
    name: easypick
    runtime: docker
    repo: https://github.com/sxrxhsab/easypick
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: easypick-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false